//   Ordt 190617.01 autogenerated file 
//   Input: test.rdl
//   Parms: openreg.parms
//   Date: Tue Aug 13 02:12:42 EDT 2019
//

import uvm_pkg::*;
`include "uvm_macros.svh"

// Register disable_check
class reg_addrmap_PICO_stats_disable_check extends uvm_reg;
  rand uvm_reg_field timer_sram;
  rand uvm_reg_field cbuf_fifo;
  rand uvm_reg_field lut_st;
  rand uvm_reg_field l0_b0;
  rand uvm_reg_field l0_b1;
  rand uvm_reg_field l0_b2;
  rand uvm_reg_field l0_b3;
  
  function new(string name = "reg_addrmap_PICO_stats_disable_check");
    super.new(name, 32, UVM_NO_COVERAGE);
  endfunction: new
  
  virtual function void build();
    this.timer_sram = new("timer_sram");
    this.timer_sram.configure(this, 1, 0, "RW", 0, 1'h0, 1, 1, 0);
    this.cbuf_fifo = new("cbuf_fifo");
    this.cbuf_fifo.configure(this, 1, 1, "RW", 0, 1'h0, 1, 1, 0);
    this.lut_st = new("lut_st");
    this.lut_st.configure(this, 1, 2, "RW", 0, 1'h0, 1, 1, 0);
    this.l0_b0 = new("l0_b0");
    this.l0_b0.configure(this, 1, 3, "RW", 1, 1'h0, 1, 1, 0);
    this.l0_b1 = new("l0_b1");
    this.l0_b1.configure(this, 1, 4, "RW", 1, 1'h0, 1, 1, 0);
    this.l0_b2 = new("l0_b2");
    this.l0_b2.configure(this, 1, 5, "RW", 1, 1'h0, 1, 1, 0);
    this.l0_b3 = new("l0_b3");
    this.l0_b3.configure(this, 1, 6, "RW", 0, 1'h0, 1, 1, 0);
  endfunction: build
  
endclass : reg_addrmap_PICO_stats_disable_check

// Register features
class reg_addrmap_PICO_stats_features extends uvm_reg;
  rand uvm_reg_field adr_logged;
  rand uvm_reg_field correctable;
  rand uvm_reg_field generator;
  rand uvm_reg_field \checker ;
  rand uvm_reg_field alt_rst_fld;
  rand uvm_reg_field default_rst_fld;
  rand uvm_reg_field wdth;
  rand uvm_reg_field version;
  rand uvm_reg_field syn_logged;
  
  function new(string name = "reg_addrmap_PICO_stats_features");
    super.new(name, 32, UVM_NO_COVERAGE);
  endfunction: new
  
  virtual function void build();
    this.adr_logged = new("adr_logged");
    this.adr_logged.configure(this, 1, 0, "RO", 0, 1'h1, 1, 0, 0);
    this.correctable = new("correctable");
    this.correctable.configure(this, 1, 1, "RO", 0, 1'h0, 1, 0, 0);
    this.generator = new("generator");
    this.generator.configure(this, 1, 3, "RO", 0, 1'h1, 1, 0, 0);
    this.\checker  = new("checker");
    this.\checker .configure(this, 1, 2, "RO", 0, 1'h1, 1, 0, 0);
    this.alt_rst_fld = new("alt_rst_fld");
    this.alt_rst_fld.configure(this, 2, 14, "RW", 0, 2'h0, 1, 1, 0);
    this.default_rst_fld = new("default_rst_fld");
    this.default_rst_fld.configure(this, 2, 16, "RW", 0, 2'h0, 1, 1, 0);
    this.wdth = new("wdth");
    this.wdth.configure(this, 5, 4, "RO", 0, 5'h7, 1, 0, 0);
    this.version = new("version");
    this.version.configure(this, 2, 30, "RO", 0, 2'h2, 1, 0, 0);
    this.syn_logged = new("syn_logged");
    this.syn_logged.configure(this, 1, 9, "RO", 0, 1'h0, 1, 0, 0);
  endfunction: build
  
endclass : reg_addrmap_PICO_stats_features

// Register log_address1
class reg_addrmap_PICO_stats_log_address1 extends uvm_reg;
  rand uvm_reg_field value;
  
  function new(string name = "reg_addrmap_PICO_stats_log_address1");
    super.new(name, 32, UVM_NO_COVERAGE);
  endfunction: new
  
  virtual function void build();
    this.value = new("value");
    this.value.configure(this, 10, 0, "RW", 1, 10'h0, 1, 1, 1);
  endfunction: build
  
endclass : reg_addrmap_PICO_stats_log_address1

// Register log_address2
class reg_addrmap_PICO_stats_log_address2 extends uvm_reg;
  rand uvm_reg_field value;
  
  function new(string name = "reg_addrmap_PICO_stats_log_address2");
    super.new(name, 32, UVM_NO_COVERAGE);
  endfunction: new
  
  virtual function void build();
    this.value = new("value");
    this.value.configure(this, 10, 0, "RW", 1, 10'h0, 1, 1, 1);
  endfunction: build
  
endclass : reg_addrmap_PICO_stats_log_address2

// Register wide_reg
class reg_addrmap_PICO_stats_wide_reg extends uvm_reg;
  rand uvm_reg_field value;
  
  function new(string name = "reg_addrmap_PICO_stats_wide_reg");
    super.new(name, 128, UVM_NO_COVERAGE);
  endfunction: new
  
  virtual function void build();
    this.value = new("value");
    this.value.configure(this, 96, 0, "RW", 1, 96'ha5a5a5a5a5a5a5a5a5a5a5a5, 1, 1, 1);
  endfunction: build
  
endclass : reg_addrmap_PICO_stats_wide_reg

// Block stats
class block_addrmap_PICO_stats extends uvm_reg_block;
  rand reg_addrmap_PICO_stats_disable_check disable_check[2];
  rand reg_addrmap_PICO_stats_features features;
  rand reg_addrmap_PICO_stats_log_address1 log_address1;
  rand reg_addrmap_PICO_stats_log_address2 log_address2;
  rand reg_addrmap_PICO_stats_wide_reg wide_reg;
  
  function new(string name = "block_addrmap_PICO_stats");
    super.new(name);
  endfunction: new
  
  virtual function void build();
    this.default_map = create_map("", 0, 16, UVM_LITTLE_ENDIAN, 1);
    foreach (this.disable_check[i]) begin
      this.disable_check[i] = new($psprintf("disable_check [%0d]",i));
      this.disable_check[i].configure(this, null, "");
      this.disable_check[i].build();
      this.default_map.add_reg(this.disable_check[i], `UVM_REG_ADDR_WIDTH'h0+i*`UVM_REG_ADDR_WIDTH'h80, "RW", 0);
    end
    this.features = new("features");
    this.features.configure(this, null, "");
    this.features.build();
    this.default_map.add_reg(this.features, `UVM_REG_ADDR_WIDTH'h100, "RW", 0);
    this.log_address1 = new("log_address1");
    this.log_address1.configure(this, null, "");
    this.log_address1.build();
    this.default_map.add_reg(this.log_address1, `UVM_REG_ADDR_WIDTH'h104, "RW", 0);
    this.log_address2 = new("log_address2");
    this.log_address2.configure(this, null, "");
    this.log_address2.build();
    this.default_map.add_reg(this.log_address2, `UVM_REG_ADDR_WIDTH'h110, "RW", 0);
    this.wide_reg = new("wide_reg");
    this.wide_reg.configure(this, null, "");
    this.wide_reg.build();
    this.default_map.add_reg(this.wide_reg, `UVM_REG_ADDR_WIDTH'h120, "RW", 0);
  endfunction: build
  
endclass : block_addrmap_PICO_stats

// Register reorder_window
class reg_addrmap_PICO_rdr_reorder_window extends uvm_reg;
  rand uvm_reg_field size;
  rand uvm_reg_field ws_enable;
  rand uvm_reg_field set_back;
  
  function new(string name = "reg_addrmap_PICO_rdr_reorder_window");
    super.new(name, 32, UVM_NO_COVERAGE);
  endfunction: new
  
  virtual function void build();
    this.size = new("size");
    this.size.configure(this, 11, 0, "RW", 0, 11'h80, 1, 1, 0);
    this.ws_enable = new("ws_enable");
    this.ws_enable.configure(this, 1, 31, "RW", 0, 1'h1, 1, 1, 0);
    this.set_back = new("set_back");
    this.set_back.configure(this, 11, 16, "RW", 0, 11'h10, 1, 1, 0);
  endfunction: build
  
endclass : reg_addrmap_PICO_rdr_reorder_window

// Register stream_reconf
class reg_addrmap_PICO_rdr_stream_reconf extends uvm_reg;
  rand uvm_reg_field stream;
  rand uvm_reg_field busy;
  
  function new(string name = "reg_addrmap_PICO_rdr_stream_reconf");
    super.new(name, 32, UVM_NO_COVERAGE);
  endfunction: new
  
  virtual function void build();
    this.stream = new("stream");
    this.stream.configure(this, 10, 0, "RW", 0, 10'h0, 1, 1, 0);
    this.busy = new("busy");
    this.busy.configure(this, 1, 16, "RO", 1, 1'h0, 1, 0, 0);
  endfunction: build
  
endclass : reg_addrmap_PICO_rdr_stream_reconf

// Register buffer
class reg_addrmap_PICO_rdr_cp_fp_wr_buffer extends uvm_reg;
  rand uvm_reg_field addr1;
  rand uvm_reg_field addr0;
  
  function new(string name = "reg_addrmap_PICO_rdr_cp_fp_wr_buffer");
    super.new(name, 32, UVM_NO_COVERAGE);
  endfunction: new
  
  virtual function void build();
    this.addr1 = new("addr1");
    this.addr1.configure(this, 11, 0, "RO", 1, 0, 1, 0, 0);
    void'(this.addr1.has_reset(.delete(1)));
    this.addr0 = new("addr0");
    this.addr0.configure(this, 11, 16, "RO", 1, 0, 1, 0, 0);
    void'(this.addr0.has_reset(.delete(1)));
  endfunction: build
  
endclass : reg_addrmap_PICO_rdr_cp_fp_wr_buffer

// Block cp_fp_wr
class block_addrmap_PICO_rdr_cp_fp_wr extends uvm_reg_block;
  rand reg_addrmap_PICO_rdr_cp_fp_wr_buffer buffer[4];
  
  function new(string name = "block_addrmap_PICO_rdr_cp_fp_wr");
    super.new(name);
  endfunction: new
  
  virtual function void build();
    this.default_map = create_map("", 0, 16, UVM_LITTLE_ENDIAN, 1);
    foreach (this.buffer[i]) begin
      this.buffer[i] = new($psprintf("buffer [%0d]",i));
      this.buffer[i].configure(this, null, "");
      this.buffer[i].build();
      this.default_map.add_reg(this.buffer[i], `UVM_REG_ADDR_WIDTH'h0+i*`UVM_REG_ADDR_WIDTH'h4, "RO", 0);
    end
  endfunction: build
  
endclass : block_addrmap_PICO_rdr_cp_fp_wr

// Register roll32_counter_reg
class reg_addrmap_PICO_rdr_roll32_counter_reg extends uvm_reg;
  rand uvm_reg_field count;
  
  function new(string name = "reg_addrmap_PICO_rdr_roll32_counter_reg");
    super.new(name, 32, UVM_NO_COVERAGE);
  endfunction: new
  
  virtual function void build();
    this.count = new("count");
    this.count.configure(this, 4, 0, "RW", 1, 4'h0, 1, 1, 1);
  endfunction: build
  
endclass : reg_addrmap_PICO_rdr_roll32_counter_reg

// Register sat32_counter_reg
class reg_addrmap_PICO_rdr_sat32_counter_reg extends uvm_reg;
  rand uvm_reg_field count;
  
  function new(string name = "reg_addrmap_PICO_rdr_sat32_counter_reg");
    super.new(name, 32, UVM_NO_COVERAGE);
  endfunction: new
  
  virtual function void build();
    this.count = new("count");
    this.count.configure(this, 4, 0, "WRC", 1, 4'h0, 1, 1, 1);
  endfunction: build
  
endclass : reg_addrmap_PICO_rdr_sat32_counter_reg

// Register rcnt_sat_log
class reg_addrmap_PICO_rdr_rcnt_sat_log extends uvm_reg;
  rand uvm_reg_field count;
  rand uvm_reg_field str;
  rand uvm_reg_field subch;
  rand uvm_reg_field en;
  
  function new(string name = "reg_addrmap_PICO_rdr_rcnt_sat_log");
    super.new(name, 32, UVM_NO_COVERAGE);
  endfunction: new
  
  virtual function void build();
    this.count = new("count");
    this.count.configure(this, 16, 0, "WRC", 1, 16'h0, 1, 1, 0);
    this.str = new("str");
    this.str.configure(this, 10, 16, "WRC", 1, 10'h0, 1, 1, 0);
    this.subch = new("subch");
    this.subch.configure(this, 5, 26, "WRC", 1, 5'h0, 1, 1, 0);
    this.en = new("en");
    this.en.configure(this, 1, 31, "RW", 0, 1'h1, 1, 1, 0);
  endfunction: build
  
endclass : reg_addrmap_PICO_rdr_rcnt_sat_log

// Block rdr
class block_addrmap_PICO_rdr extends uvm_reg_block;
  rand reg_addrmap_PICO_rdr_reorder_window reorder_window;
  rand reg_addrmap_PICO_rdr_stream_reconf stream_reconf;
  rand block_addrmap_PICO_rdr_cp_fp_wr cp_fp_wr;
  rand reg_addrmap_PICO_rdr_roll32_counter_reg roll32_counter_reg;
  rand reg_addrmap_PICO_rdr_sat32_counter_reg sat32_counter_reg;
  rand reg_addrmap_PICO_rdr_rcnt_sat_log rcnt_sat_log;
  
  function new(string name = "block_addrmap_PICO_rdr");
    super.new(name);
  endfunction: new
  
  virtual function void build();
    this.default_map = create_map("", 0, 16, UVM_LITTLE_ENDIAN, 1);
    this.reorder_window = new("reorder_window");
    this.reorder_window.configure(this, null, "");
    this.reorder_window.build();
    this.default_map.add_reg(this.reorder_window, `UVM_REG_ADDR_WIDTH'h0, "RW", 0);
    this.stream_reconf = new("stream_reconf");
    this.stream_reconf.configure(this, null, "");
    this.stream_reconf.build();
    this.default_map.add_reg(this.stream_reconf, `UVM_REG_ADDR_WIDTH'h4, "RW", 0);
    this.cp_fp_wr = new("cp_fp_wr");
    this.cp_fp_wr.configure(this, "");
    this.cp_fp_wr.build();
    this.default_map.add_submap(this.cp_fp_wr.default_map, `UVM_REG_ADDR_WIDTH'h21c0);
    this.roll32_counter_reg = new("roll32_counter_reg");
    this.roll32_counter_reg.configure(this, null, "");
    this.roll32_counter_reg.build();
    this.default_map.add_reg(this.roll32_counter_reg, `UVM_REG_ADDR_WIDTH'h21d0, "RW", 0);
    this.sat32_counter_reg = new("sat32_counter_reg");
    this.sat32_counter_reg.configure(this, null, "");
    this.sat32_counter_reg.build();
    this.default_map.add_reg(this.sat32_counter_reg, `UVM_REG_ADDR_WIDTH'h21d4, "RW", 0);
    this.rcnt_sat_log = new("rcnt_sat_log");
    this.rcnt_sat_log.configure(this, null, "");
    this.rcnt_sat_log.build();
    this.default_map.add_reg(this.rcnt_sat_log, `UVM_REG_ADDR_WIDTH'h21d8, "RW", 0);
  endfunction: build
  
endclass : block_addrmap_PICO_rdr

// extra_reg name
class reg_addrmap_PICO_extra_reg extends uvm_reg;
  rand uvm_reg_field value;
  
  function new(string name = "reg_addrmap_PICO_extra_reg");
    super.new(name, 32, UVM_NO_COVERAGE);
  endfunction: new
  
  virtual function void build();
    this.value = new("value");
    this.value.configure(this, 32, 0, "RW", 0, 0, 1, 1, 1);
    void'(this.value.has_reset(.delete(1)));
  endfunction: build
  
endclass : reg_addrmap_PICO_extra_reg

// Base block
class block_addrmap_PICO extends uvm_reg_block;
  rand block_addrmap_PICO_stats stats;
  rand block_addrmap_PICO_rdr rdr;
  rand reg_addrmap_PICO_extra_reg extra_reg;
  
  function new(string name = "block_addrmap_PICO");
    super.new(name);
  endfunction: new
  
  virtual function void build();
    this.default_map = create_map("", `UVM_REG_ADDR_WIDTH'h0, 16, UVM_LITTLE_ENDIAN, 1);
    this.stats = new("stats");
    this.stats.configure(this, "");
    this.stats.build();
    this.default_map.add_submap(this.stats.default_map, `UVM_REG_ADDR_WIDTH'h1000);
    this.rdr = new("rdr");
    this.rdr.configure(this, "");
    this.rdr.build();
    this.default_map.add_submap(this.rdr.default_map, `UVM_REG_ADDR_WIDTH'h4000);
    this.extra_reg = new("extra_reg");
    this.extra_reg.configure(this, null, "");
    this.extra_reg.build();
    this.default_map.add_reg(this.extra_reg, `UVM_REG_ADDR_WIDTH'h61dc, "RW", 0);
  endfunction: build
  
endclass : block_addrmap_PICO
