#if !defined(_csc2cmac_data_if_IFACE)
#define _csc2cmac_data_if_IFACE

#define FLOW_csc2cmac_data_if valid

#define SIG_csc2cmac_data_if_batch_index_WIDTH 5
#define SIG_csc2cmac_data_if_batch_index_FIELD 4:0
#define SIG_csc2cmac_data_if_stripe_st_WIDTH 1
#define SIG_csc2cmac_data_if_stripe_st_FIELD 0:0
#define SIG_csc2cmac_data_if_stripe_end_WIDTH 1
#define SIG_csc2cmac_data_if_stripe_end_FIELD 0:0
#define SIG_csc2cmac_data_if_channel_end_WIDTH 1
#define SIG_csc2cmac_data_if_channel_end_FIELD 0:0
#define SIG_csc2cmac_data_if_layer_end_WIDTH 1
#define SIG_csc2cmac_data_if_layer_end_FIELD 0:0
#define SIG_csc2cmac_data_if_mask_WIDTH 32
#define SIG_csc2cmac_data_if_mask_FIELD 31:0
#define SIG_csc2cmac_data_if_data0_WIDTH 8
#define SIG_csc2cmac_data_if_data0_FIELD 7:0
#define SIG_csc2cmac_data_if_data1_WIDTH 8
#define SIG_csc2cmac_data_if_data1_FIELD 7:0
#define SIG_csc2cmac_data_if_data2_WIDTH 8
#define SIG_csc2cmac_data_if_data2_FIELD 7:0
#define SIG_csc2cmac_data_if_data3_WIDTH 8
#define SIG_csc2cmac_data_if_data3_FIELD 7:0
#define SIG_csc2cmac_data_if_data4_WIDTH 8
#define SIG_csc2cmac_data_if_data4_FIELD 7:0
#define SIG_csc2cmac_data_if_data5_WIDTH 8
#define SIG_csc2cmac_data_if_data5_FIELD 7:0
#define SIG_csc2cmac_data_if_data6_WIDTH 8
#define SIG_csc2cmac_data_if_data6_FIELD 7:0
#define SIG_csc2cmac_data_if_data7_WIDTH 8
#define SIG_csc2cmac_data_if_data7_FIELD 7:0
#define SIG_csc2cmac_data_if_data8_WIDTH 8
#define SIG_csc2cmac_data_if_data8_FIELD 7:0
#define SIG_csc2cmac_data_if_data9_WIDTH 8
#define SIG_csc2cmac_data_if_data9_FIELD 7:0
#define SIG_csc2cmac_data_if_data10_WIDTH 8
#define SIG_csc2cmac_data_if_data10_FIELD 7:0
#define SIG_csc2cmac_data_if_data11_WIDTH 8
#define SIG_csc2cmac_data_if_data11_FIELD 7:0
#define SIG_csc2cmac_data_if_data12_WIDTH 8
#define SIG_csc2cmac_data_if_data12_FIELD 7:0
#define SIG_csc2cmac_data_if_data13_WIDTH 8
#define SIG_csc2cmac_data_if_data13_FIELD 7:0
#define SIG_csc2cmac_data_if_data14_WIDTH 8
#define SIG_csc2cmac_data_if_data14_FIELD 7:0
#define SIG_csc2cmac_data_if_data15_WIDTH 8
#define SIG_csc2cmac_data_if_data15_FIELD 7:0
#define SIG_csc2cmac_data_if_data16_WIDTH 8
#define SIG_csc2cmac_data_if_data16_FIELD 7:0
#define SIG_csc2cmac_data_if_data17_WIDTH 8
#define SIG_csc2cmac_data_if_data17_FIELD 7:0
#define SIG_csc2cmac_data_if_data18_WIDTH 8
#define SIG_csc2cmac_data_if_data18_FIELD 7:0
#define SIG_csc2cmac_data_if_data19_WIDTH 8
#define SIG_csc2cmac_data_if_data19_FIELD 7:0
#define SIG_csc2cmac_data_if_data20_WIDTH 8
#define SIG_csc2cmac_data_if_data20_FIELD 7:0
#define SIG_csc2cmac_data_if_data21_WIDTH 8
#define SIG_csc2cmac_data_if_data21_FIELD 7:0
#define SIG_csc2cmac_data_if_data22_WIDTH 8
#define SIG_csc2cmac_data_if_data22_FIELD 7:0
#define SIG_csc2cmac_data_if_data23_WIDTH 8
#define SIG_csc2cmac_data_if_data23_FIELD 7:0
#define SIG_csc2cmac_data_if_data24_WIDTH 8
#define SIG_csc2cmac_data_if_data24_FIELD 7:0
#define SIG_csc2cmac_data_if_data25_WIDTH 8
#define SIG_csc2cmac_data_if_data25_FIELD 7:0
#define SIG_csc2cmac_data_if_data26_WIDTH 8
#define SIG_csc2cmac_data_if_data26_FIELD 7:0
#define SIG_csc2cmac_data_if_data27_WIDTH 8
#define SIG_csc2cmac_data_if_data27_FIELD 7:0
#define SIG_csc2cmac_data_if_data28_WIDTH 8
#define SIG_csc2cmac_data_if_data28_FIELD 7:0
#define SIG_csc2cmac_data_if_data29_WIDTH 8
#define SIG_csc2cmac_data_if_data29_FIELD 7:0
#define SIG_csc2cmac_data_if_data30_WIDTH 8
#define SIG_csc2cmac_data_if_data30_FIELD 7:0
#define SIG_csc2cmac_data_if_data31_WIDTH 8
#define SIG_csc2cmac_data_if_data31_FIELD 7:0

#endif // !defined(_csc2cmac_data_if_IFACE)